id:586
user_name:10.44.163.70
user_id:10.44.163.70-c3deec0af89e4903
script:APP: responder SAAB
start_time:1663161988028
command:/home/pi/rise_drones_dev/start_scripts/app_responder_saab.sh
output_format:terminal
exit_code:0
>>>>>  OUTPUT STARTED <<<<<
Configuration file found at "/home/pi/.rise_drones/.config"
2022-09-14 15:26:29,396: INFO [dss.auxiliaries.logging] app_ussp_mission.py 1.3.0 v1.3.0-32-g666a8f6
2022-09-14 15:26:29,397: INFO [dss.auxiliaries.logging] arguments: ['--crm=10.44.160.10:16300', '--app_ip=10.44.163.22', '--mission=../../../rise_drones_dev/mission/missions/USSP_SAAB_CAMERA_first_responder.json', '--stdout', '--log=info', '--capabilities', 'RTK', 'VIDEO', '--without-negotiation']
2022-09-14 15:26:29,430: INFO [dss.client.client_lib] DSS client_lib v1.3.0-32-g666a8f6
2022-09-14 15:26:29,472: INFO [dss.client.crm_api] CRM crm_api v1.3.0-32-g666a8f6
2022-09-14 15:26:29,480: INFO [dss.app_ussp_mission] Reply socket is listening on: 16301
2022-09-14 15:26:30,222: INFO [dss.app_ussp_mission] App da272 listening on *:16301
2022-09-14 15:26:30,223: INFO [dss.app_ussp_mission] App registered with CRM: da272
2022-09-14 15:26:30,224: INFO [dss.app_ussp_mission] App connecting to USSP: ussp.itn.liu.se
2022-09-14 15:26:30,224: INFO [dss.client.ussp_client_lib] U-space Client Lib
2022-09-14 15:26:30,225: INFO [dss.client.ussp_client_api] USSP Client API
2022-09-14 15:26:30,483: INFO [dss.client.dss_api] DSS dss_api v1.3.0-32-g666a8f6
2022-09-14 15:26:31,212: INFO [dss.client.client_lib] Connection to DSS established on tcp://10.44.163.22:16345
2022-09-14 15:26:31,213: INFO [dss.app_ussp_mission] Connected as owner of drone: [dss271]
2022-09-14 15:26:31,218: INFO [dss.app_ussp_mission] Setup dss info stream
2022-09-14 15:26:31,223: INFO [dss.app_ussp_mission] Waiting for the drone to stream its current position
2022-09-14 15:26:31,618: INFO [dss.app_ussp_mission] Start position received, altitude difference: -0.7711691284179665
2022-09-14 15:26:33,736: INFO [dss.auxiliaries.zmq] [da272] [req] reconnecting...
2022-09-14 15:26:33,738: ERROR [dss.app_ussp_mission] NoAnswer when sending: {'fcn': 'upload_mission_LLA', 'id': 'da272', 'mission': {'id0': {'lat': 58.40946129427022, 'lon': 15.659288752837597, 'alt': 25, 'heading': 'course', 'alt_type': 'relative', 'speed': 5.0}, 'id1': {'lat': 58.40946129427022, 'lon': 15.659288752837597, 'alt': 15, 'heading': 'course', 'alt_type': 'relative', 'speed': 5.0}, 'status': 'pending', 'speed': 5.0}} to 10.44.163.22:16345
2022-09-14 15:26:33,740: INFO [dss.app_ussp_mission] Closing down...
2022-09-14 15:26:33,741: INFO [dss.app_ussp_mission] Unregister from CRM
2022-09-14 15:26:33,911: INFO [dss.app_ussp_mission] Stopped thread and closed info socket
2022-09-14 15:26:34,222: WARNING [dss.auxiliaries.zmq] [req] [crm] no response to heartbeat (1)
2022-09-14 15:26:34,223: INFO [dss.app_ussp_mission] CRM socket closed
2022-09-14 15:26:34,489: INFO [dss.app_ussp_mission] Reply socket closed, thread exit
2022-09-14 15:26:34,725: INFO [dss.app_ussp_mission] Closing socket to DSS
2022-09-14 15:26:35,743: INFO [dss.auxiliaries.zmq] [da272] [req] reconnecting...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/pi/rise_drones/src/app/dss/auxiliaries/zmq.py", line 282, in _send_and_receive
    json_reply = self._socket.recv_json()
  File "/home/pi/.venv/rise_drones/lib/python3.9/site-packages/zmq/sugar/socket.py", line 823, in recv_json
    msg = self.recv(flags)
  File "zmq/backend/cython/socket.pyx", line 781, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 817, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/rise_drones/src/app/dss/auxiliaries/zmq.py", line 336, in _main_heartbeat
    answer = self.send_and_receive(heartbeat_msg)
  File "/home/pi/rise_drones/src/app/dss/auxiliaries/zmq.py", line 295, in send_and_receive
    return self._send_and_receive(msg)
  File "/home/pi/rise_drones/src/app/dss/auxiliaries/zmq.py", line 285, in _send_and_receive
    raise dss.auxiliaries.exception.NoAnswer(msg, self.ip, self.port)
dss.auxiliaries.exception.NoAnswer
